// Code generated by command: go run asm.go -out add.s -stubs stub.go. DO NOT EDIT.

package goasm

// Add the arrays x and y and store the result into z.
func Add(x []uint64, y []uint64, z []uint64)
